server:
  port: 8081
# spring 配置
spring:
  application:
    name: spring-cloud-provider-8081
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.227.11:3306/platform_xhcrm?characterEncoding=utf-8&useUnicode=true&allowMultiQueries=true&useSSL=false
    username: *
    password: *
# mybatis 配置
mybatis:
  type-aliases-package: com.aking.cloud.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/*Mapper.xml

# eureka 服务注册
eureka:
  client:
    service-url:
      # 单机
      # defaultZone: http://localhost:7001/eureka
      # eureka 集群
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
    instance:
      instance-id: spring-cloud-provider-8081 # 修改 eureka 默认描述信息

# actuator info配置
info:
  app.name: spring-cloud-provider-8081
  company.name: www.aking.com
